export enum passwordActionsEnum {
  REGISTER_NEW_USER = 'CARDS/REGISTER_AND_RECOVERY/REGISTER_NEW_USER',
  SET_REGISTER_ERROR = 'CARDS/REGISTER_AND_RECOVERY/SET_REGISTER_ERROR',
  SET_RECOVERY_PASS_INFO = 'CARDS/REGISTER_AND_RECOVERY/SET_RECOVERY_PASS_INFO',
  SET_NEW_PASS_INFO = 'CARDS/REGISTER_AND_RECOVERY/SET_NEW_PASS_INFO',
  SET_NEW_ERROR = 'CARDS/REGISTER_AND_RECOVERY/SET_NEW_ERROR',
}