export enum AppFormReducer {
  SET_STATUS = 'CARDS/APP/SET-STATUS',
  SET_VISIBLE = 'CARDS/APP/SET-VISIBLE',
  SET_GLOBAL_ERROR = 'CARDS/APP/SET_GLOBAL_ERROR',
  SET_IS_LOAD = 'CARDS/APP/SET_IS_LOAD',
}