export enum cardsActionsEnum {
  SET_CARDS = 'CARDS/CARDS/SET_CARDS',
  SET_PAGE = 'CARDS/CARDS/PAGE',
  SET_PAGE_COUNT = 'CARDS/CARDS/PAGE_COUNT',
  SEARCH_CARDS = 'CARDS/CARDS/SEARCH_CARDS',
  UPDATE_CARDS = 'CARDS/CARDS/UPDATE_CARDS',
  GRADE_CARD = 'CARDS/CARDS/GRADE_CARD',
  SET_CARD_MODE = 'CARDS/CARDS/CARD_MODE',
}