export enum packsActionsEnum {
  SET_PACKS = 'CARDS/PACKS/SET_PACKS',
  SET_ALL_USER_ID_CARDS = 'CARDS/PACKS/SET_ALL_USER_ID',
  SET_MIN_CARDS_COUNT = 'CARDS/PACKS/SET_MIN_CARDS_COUNT',
  SET_MAX_CARDS_COUNT = 'CARDS/PACKS/SET_MAX_CARDS_COUNT',
  SEARCH_BY_PACK_NAME = 'CARDS/PACKS/SEARCH_BY_PACK_NAME',
  SET_CURRENT_PAGE = 'CARDS/PACKS/SET_CURRENT_PAGE',
  SET_PAGE_COUNT = 'CARDS/PACKS/SET_PAGE_COUNT',
  SET_UPDATED_FILTER = 'CARDS/PACKS/SET_UPDATED_FILTER',
  SET_PACKS_MODE = 'CARDS/PACKS/SET_PACKS_MODE',
}